/**
  Endpoints related to students
**/

const router = require("express").Router();
const {
  getAllStudents,
  getStudentById,
  getStudentsByClassroom,
  addNewStudent,
  deleteStudentById,
} = require("./studentsHandlers");

//.......................................//
//STUDENT ROUTES                         //
//.......................................//
router.get("/students", getAllStudents); // get all students in database
router.get("/students/:id", getStudentById); //get a student by id
router.get("/students/:classroom_id", getStudentsByClassroom); //get all students from a classroom
router.post("/students", addNewStudent); //when teacher adds a student to their list (BODY: id(uuid4), givenName, surname, userName (autgenerated), password (autogenerated), classRoomId, booksCheckedOut (empty array to start), waitingList (empty array to start))
router.delete("/students/:id", deleteStudentById); //removes student by Id

//may modify this stuff when checking out a book on the library side
// router.patch("/student/:id/booksCheckedOut", modifyBookesCheckedOutByStudent); //add or remove books checked out by student
// router.patch("/student/:id/waitingList", modifyWaitingListByStudent); //add or remove book on student waiting list

//NOT SURE IF NEEDED (MAY BE ABLE TO GET INFO FROM GET STUDENT BY ID)...............................................//
// router.get("/student/:id/classroom", getClassroomByStudent); //not sure if needed                                    //
// router.get("/student/:id/booksCheckedOut", getbooksCheckedOutByStudent); //get books checked out by student          //
// router.get("/student/:id/waitingList", getWaitingListByStudent); //get waiting list by student                       //
//..................................................................................................................//

module.exports = router;
